version: '3.6'

services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_1_NAME}_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-creed1120}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_1_NAME:-wordpress-1}

  wordpress_1:
    depends_on:
      - db
    image: wordpress:${WORDPRESS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_1_NAME:-wordpress-1}
    ports:
      - "8086:80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_1_NAME:-wordpress-1}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-db}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
    working_dir: /var/www/html
    volumes:
      - ${WORDPRESS_1_DATA_DIR}:/var/www/html
      - ${WORDPRESS_HOME_DATA_DIR}/wp-content-1:/var/www/html/wp-content
      - ${WORDPRESS_HOME_DATA_DIR:-./uploads.ini}:/usr/local/etc/php/conf.d/uploads.ini

  # db_2:
  #   image: mariadb:${MARIADB_VERSION:-latest}
  #   container_name: ${COMPOSE_PROJECT_2_NAME}_mysql
  #   volumes:
  #     - db_data_2:/var/lib/mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password2}
  #     - MYSQL_USER=${DATABASE_2_USER:-creed}
  #     - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password2}
  #     - MYSQL_DATABASE=${COMPOSE_PROJECT_2_NAME:-wordpress-2}

  # wordpress_2:
  #   depends_on:
  #     - db_2
  #   image: wordpress:${WORDPRESS_VERSION:-latest}
  #   container_name: ${COMPOSE_PROJECT_2_NAME:-wordpress-2}
  #   ports:
  #     - "8088:80"
  #   restart: always
  #   environment:
  #     - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_2_NAME:-wordpress-2}
  #     - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
  #     - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-db}
  #     - WORDPRESS_DB_USER=${DATABASE_USER:-root}
  #     - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
  #   working_dir: /var/www/html
  #   volumes:
  #     - ${WORDPRESS_2_DATA_DIR}:/var/www/html
  #     - ${WORDPRESS_HOME_DATA_DIR}/wp-content-2:/var/www/html/wp-content
  #     - ${WORDPRESS_HOME_DATA_DIR:-./uploads.ini}:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
      container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
      restart: always
      ports:
        - ${PHPMYADMIN_PORT}:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}

  # phpmyadmin_2:
  #     depends_on:
  #       - db_2
  #     image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
  #     container_name: ${COMPOSE_PROJECT_2_NAME}_phpmyadmin
  #     restart: always
  #     ports:
  #       - ${PHPMYADMIN_2_PORT}:80
  #     environment:
  #       PMA_HOST: db_2
  #       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}

volumes:
  db_data:
  db_data_2: